# Generated by Django 4.0.3 on 2022-04-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='total_sqm',
            new_name='terrain_sqm',
        ),
    ]
