# Generated by Django 4.0.3 on 2022-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0003_alter_profile_tipo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
