# Generated by Django 4.0.3 on 2022-04-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0005_alter_profile_tipo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
