# Generated by Django 4.0.3 on 2022-04-05 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('picture', models.URLField(default='Sin imagen disponible')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_kind', models.CharField(choices=[('arrendatar', 'Arrendatario'), ('arrendador', 'Arrendador'), (None, 'Sin información')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('builded_sqm', models.IntegerField()),
                ('total_sqm', models.IntegerField()),
                ('parkings', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('adress', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=30)),
                ('rent_price', models.FloatField()),
                ('property_kind', models.CharField(choices=[('CASA', 'Casa'), ('DPTO', 'Departamento'), ('PARC', 'Parcela'), (None, 'Sin información')], max_length=4)),
                ('users', models.ManyToManyField(related_name='properties', through='rent_page.Contract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.TextField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_page.property', verbose_name='id de la propiedad')),
                ('user_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='rut del usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_page.property', verbose_name='id de la propiedad'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='rut del usuario'),
        ),
    ]
